default: &default
  appName: "Data Demo (Ruby)"
  adminBaseURL: http://localhost:5399
  adminJwtSecret: <adminJwtSecret>

  userService:
    urlBase: <urlBase>
    username: <username>
    password: <password>

  adminSSO:
    baseURL: https://sso.staging.fangcha.net
    clientId: <clientId>
    clientSecret: <clientSecret>
    authorizePath: /api/v1/oauth/authorize
    tokenPath: /api/v1/oauth/token
    logoutPath: /api/v1/logout
    scope: basic
    callbackUri: http://localhost:5399/api-302/auth-sdk/v1/handle-sso
    userInfoURL: https://sso.staging.fangcha.net/api/v1/oauth/user-info

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
